import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

// Mock data for projects
const mockProjects = [
  { id: "1", name: "Project Alpha", status: "active", createdAt: "2023-10-01T00:00:00Z" },
  { id: "2", name: "Project Beta", status: "completed", createdAt: "2023-09-15T00:00:00Z" },
  { id: "3", name: "Project Gamma", status: "active", createdAt: "2023-11-05T00:00:00Z" },
];

// GET handler for fetching projects
export async function GET() {
  // TODO: Replace with actual Prisma query when Project model is added to schema
  return NextResponse.json(mockProjects);
}

// POST handler for creating a new project
export async function POST(request: NextRequest) {
  const body = await request.json();

  // TODO: Replace with actual Prisma query when Project model is added to schema
  const newProject = {
    id: "4", // This should be generated by the database
    name: body.name,
    status: "active",
    createdAt: new Date().toISOString(),
  };

  // Mock response
  return NextResponse.json(newProject, { status: 201 });
}
