import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

// Mock data for projects
const mockProjects = [
  { id: "1", name: "Project Alpha", startDate: "2023-01-01", endDate: "2023-12-31" },
  { id: "2", name: "Project Beta", startDate: "2023-02-01", endDate: "2023-11-30" },
];

// GET handler for fetching projects
export async function GET() {
  // TODO: Replace with actual Prisma query when Project model is added to schema
  return NextResponse.json(mockProjects);
}

// POST handler for creating a new project
export async function POST(request: NextRequest) {
  const { name, startDate, endDate, assignees } = await request.json();

  // TODO: Replace with actual Prisma query when Project model is added to schema
  const newProject = {
    id: "3", // This should be generated by the database
    name,
    startDate,
    endDate,
    assignees,
  };

  // Mock response
  return NextResponse.json(newProject, { status: 201 });
}
